### ISSUE TITLE
Spaces in path

### ISSUE THREAD

**Issue by iceman** [rastersize/CDEvents#1]
CDEvent URLs come back as null if the path has any spaces.  I think you need to run the string through stringByAddingPercentEscapesUsingEncoding before converting to NSURL as below.

```
NSString *escapedEventPath = [eventPath stringByAddingPercentEscapesUsingEncoding: NSUTF8StringEncoding];
NSURL *eventURL = [NSURL URLWithString:escapedEventPath];
```

(not sure if NSUTF8StringEncoding is the best encoding)

**Comment by rastersize** [comment]
Hi,

First of all, thanks for your report. It truly makes me happy to hear that there are at least one person out there other than myself using my code. It made my day!

Regarding your issue, I'm pretty sure I've found the the cause (I didn't escape certain characters when creating the NSURL objects, such as spaces) and fixed it. See the commit f5c9eac4ef71df579c083a6ca604783df3979341 for the diff. I've also created a new tag (`1.1.1`) and pushed the changes to `master` (the, so called, stable branch), `develop` (default branch) contains the fix too.

Please let me know if you have any other issues or comments on the code and I'll see what I can do.
