### ISSUE TITLE
Please add and update podspec

### ISSUE THREAD

**Issue by dwlnetnl** [rastersize/CDEvents#13]
I've written a podspec for CDEvents: https://github.com/dwlnetnl/CocoaPodsSpecs/commit/76b2b5e821c995c94f56de399cf4eb88a8413702

Please add and update the spec so we can easily include CDEvents in projects!

**Comment by rastersize** [comment]
Thanks, I changed it a bit as 1.1.2 targets OS X 10.5. I’m thinking I will take this opportunity to tag version 1.2.0 which will require 10.6, ARC and blocks so check back in an hour or so if you want that stuff.

**Comment by rastersize** [comment]
The ARC/blocks 1.2.0 version has been tagged, also updated the [podspec](https://github.com/rastersize/CDEvents/blob/46f63c8ccd34fe51f6093189e40a996a11078d7c/CDEvents.podspec) (hopefully that looks ok to you?).

**Comment by dwlnetnl** [comment]
It seems that the spec is only valid if the license file is part of the project.

**Comment by rastersize** [comment]
By project, do you mean the Xcode project?
Guessing it could be changed to just `s.license  = 'MIT'` (which is what [AFNetworking does](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking.podspec#L4)). That would work just as fine for me.

**Comment by dwlnetnl** [comment]
Yeah I mean the Xcode project. So far as I can see there should no problem with the spec, with the s.license = 'MIT' too.

Do you have CocoaPods currently installed? Because you need to push it in the http://github.com/CocoaPods/Specs repo. I can push it for this time because I just got write access.

**Comment by dwlnetnl** [comment]
Or request a pull from a forked specs repo.

**Comment by rastersize** [comment]
Think the easiest will be to change the license directive in the spec, just committed that.

I don’t have CocoaPods installed, I will make sure to fork the specs repo so that I can keep the spec updated. If you want please go ahead and push it, otherwise I’ll open a pull request.

**Comment by dwlnetnl** [comment]
Okay, I push it.

**Comment by rastersize** [comment]
Thanks!
