### ISSUE TITLE
Get all File and Folder notification using CDEvents (FSEvents wrapper )?

### ISSUE THREAD

**Issue by Bhushan30** [rastersize/CDEvents#25]
I had implemented file watcher part using CDEvents : It is notifying all changes. But I want only file created, deleted, renamed, modified events notification and also folder created,deleted,renamed notification? How to get exact these notification? And How to used it? I don't need all notification.

output I get is this:

2014-02-12 13:09:14.607 TestCDEvents10-2[5189:503] CDEvents { eventId = 3348870, eventPath = /Users/user1/.Trash/untitled folder 1.09.13 PM, eventFlags = 133120 }
Its notifying me changed in the form of event_id, event_path and event_flags. But how should I get information which event is raise. Its not giving any details like File created event occurs, File Renamed event occur etc.

How should i get proper information about which event is raised?
Can we get notification type(like file created, file deleted etc.) using eventFlags? or is there any other way for this?

Please give me direction. Thanks...

**Comment by rastersize** [comment]
You should be able to specify which types of events you want to receive by specifying the `streamCreationFlags` using the full init method:

``` Objective-C
// File: CDEvents.h
- (id)initWithURLs:(NSArray *)URLs
             block:(CDEventsEventBlock)block
         onRunLoop:(NSRunLoop *)runLoop
sinceEventIdentifier:(CDEventIdentifier)sinceEventIdentifier
notificationLantency:(CFTimeInterval)notificationLatency
ignoreEventsFromSubDirs:(BOOL)ignoreEventsFromSubDirs
       excludeURLs:(NSArray *)exludeURLs
streamCreationFlags:(CDEventsEventStreamCreationFlags)streamCreationFlags;
```

Have a look at Apple’s documentation on [`FSEventStreamCreateFlags`](https://developer.apple.com/library/mac/documentation/Darwin/Reference/FSEvents_Ref/Reference/reference.html#//apple_ref/doc/uid/TP40004723-CHFSEventshConstants-DontLinkElementID_3) for a list of available flags. The flag you’re probably most interested in is `kFSEventStreamCreateFlagFileEvents`.

When it comes to the events they do provide this data and to retrieve it you can, as you guessed, check the `eventFlags` property. Either manually (have a look at the docs on [`FSEventStreamEventFlags`](https://developer.apple.com/library/mac/documentation/Darwin/Reference/FSEvents_Ref/Reference/reference.html#//apple_ref/doc/uid/TP40004723-CHFSEventshConstants-DontLinkElementID_4) for all the possible flags) or using one or more of the getters provided by the `CDEvent` class. For example the method `isCreated` checks whether the event represent a file creation.

The event flags documentation is unfortunately a bit lacking. The “new” file event flags are only exposed in the `FSEvents.h` file and still haven’t been documented by Apple.
