### ISSUE TITLE
Returning different value of _eventsFlags in CDEvents(FSEvents wrapper )?

### ISSUE THREAD

**Issue by Bhushan30** [rastersize/CDEvents#26]
I implemented file watcher part using CDEvents
Its giving output like this :

2014-02-11 16:08:38.725 TestCDEvent10-2[2995:403] 
CDEvent { 
          eventId = 3182336, 
          eventPath = /Users/user1/Desktop, 
          eventFlags = 131328 
        }
Value of enum is :

kFSEventStreamEventFlagItemCreated       = 0x00000100,
kFSEventStreamEventFlagItemRemoved       = 0x00000200,
kFSEventStreamEventFlagItemInodeMetaMod  = 0x00000400,
kFSEventStreamEventFlagItemRenamed       = 0x00000800,
kFSEventStreamEventFlagItemModified      = 0x00001000,
kFSEventStreamEventFlagItemFinderInfoMod = 0x00002000,
kFSEventStreamEventFlagItemChangeOwner   = 0x00004000,
kFSEventStreamEventFlagItemXattrMod      = 0x00008000,
kFSEventStreamEventFlagItemIsFile        = 0x00010000,
kFSEventStreamEventFlagItemIsDir         = 0x00020000,
kFSEventStreamEventFlagItemIsSymlink     = 0x00040000

It register CDEvents flags with above value, and If we run the application and change the file contents or renamed the file the value of _eventsFlags is different. So i unable to know which file event is occured?

Please provide me direction...

**Comment by rastersize** [comment]
I’m guessing you’re using an init-method which does not allow you to specify the event stream creation flags or you’re using the `kCDEventsDefaultEventStreamFlags` constant. `FSEvents` which `CDEvents` is using “internally” (yes it’s a very leaky abstraction…) does not provide the path of file which was changed unless you explicitly set the event stream creation flags to include `kFSEventStreamCreateFlagFileEvents`. The file events flag was introduced in 10.7 so you must be targeting that version of OS X (or a newer).

You could then use one of the longer init-methods to tell `CDEvents`/`FSEvents` that you want file level events. For example:

``` Objective-C
CDEvents *watcher = [[CDEvents alloc]
           initWithURLs:@[ watchUrl ]
                  block:^(CDEvents *watcher, CDEvent *event) { NSLog(@"%@", event); }
              onRunLoop:[NSRunLoop currentRunLoop]
   sinceEventIdentifier:kCDEventsSinceEventNow
   notificationLantency:CD_EVENTS_DEFAULT_NOTIFICATION_LATENCY
ignoreEventsFromSubDirs:CD_EVENTS_DEFAULT_IGNORE_EVENT_FROM_SUB_DIRS
            excludeURLs:@[ excludeThisUrl, andThatUrl ]
    streamCreationFlags:(kCDEventsDefaultEventStreamFlags + kFSEventStreamCreateFlagFileEvents)];
```

I’d also suggest reading [Apple’s documentation on `FSEvents`](https://developer.apple.com/library/mac/documentation/Darwin/Reference/FSEvents_Ref/Reference/reference.html) to get to know it.
